---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shared-resources
spec:
  interval: 1h
  path: "./kubernetes/apps/minecraft/server/shared/"
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: minecraft
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: java-cozy-vanilla
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: java-cozy-vanilla
      app: minecraft-server
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: java-cozy-vanilla
      namespace: minecraft
  interval: 1h
  path: "./kubernetes/apps/minecraft/server/java-cozy-vanilla/"
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: minecraft
  timeout: 5m
  dependsOn:
    - name: shared-resources
      namespace: minecraft
