---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-router
spec:
  timeout: 30s
  chartRef:
    kind: OCIRepository
    name: minecraft-router
  interval: 30m
  values:
    controllers:
      minecraft-router:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsGroup: 2000
            runAsNonRoot: true
            runAsUser: 2000

        containers:
          app:
            image:
              repository: itzg/mc-router
              tag: "1.39.1"
            args:
              - --in-kube-cluster
            env:
              KUBE_NAMESPACE: minecraft

            probes:
              liveness: &probe
                enabled: true
              readiness: *probe

            resources:
              requests:
                cpu: 50m
                memory: 32Mi
              limits:
                cpu: 150m
                memory: 100Mi

    service:
      minecraft-router:
        ports:
          minecraft:
            port: 25565
            protocol: TCP

    route:
      minecraft-router:
        kind: TCPRoute
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: minecraft
        rules:
          - backendRefs:
              - identifier: minecraft-router
                port: minecraft

    serviceAccount:
      minecraft-router: {}

    rbac:
      roles:
        minecraft-router-service-watcher:
          type: ClusterRole
          rules:
            - apiGroups: [""]
              resources: ["services"]
              verbs: ["get", "list", "watch"]
      bindings:
        minecraft-router-service-watcher:
          type: ClusterRoleBinding
          roleRef:
            identifier: minecraft-router-service-watcher
          subjects:
            - identifier: minecraft-router
