---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externaldns-home
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: keyname
      remoteRef:
        key: &item PowerDNS - TSIG (internal-update-key)
        property: keyname
    - secretKey: secret
      remoteRef:
        key: *item
        property: secret
    - secretKey: algorithm
      remoteRef:
        key: *item
        property: algorithm
