---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: externaldns-home
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: external-dns-home
      interval: 30m

  values:
    fullnameOverride: &name externaldns-home
    domainFilters:
      - int.kreigan.com
    extraArgs:
      - --ignore-ingress-tls-spec
      - --rfc2136-host=10.1.21.3
      - --rfc2136-port=53
      - --rfc2136-zone=int.kreigan.com
      - --rfc2136-tsig-keyname=$(BIND_TSIG_KEYNAME)
      - --rfc2136-tsig-secret=$(BIND_TSIG_SECRET)
      - --rfc2136-tsig-secret-alg=$(BIND_TSIG_ALG)
      - --rfc2136-tsig-axfr
    podAnnotations:
      secret.reloader.stakater.com/reload: &secret externaldns-home
    provider:
      name: rfc2136
    policy: sync
    env:
      - name: BIND_TSIG_KEYNAME
        valueFrom:
          secretKeyRef:
            name: *secret
            key: keyname
      - name: BIND_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: *secret
            key: secret
      - name: BIND_TSIG_ALG
        valueFrom:
          secretKeyRef:
            name: *secret
            key: algorithm
    resources:
      requests:
        cpu: 16m
        memory: 90M
      limits:
        memory: 90M
    serviceMonitor:
      enabled: true
    sources:
      - gateway-httproute
      - service
    triggerLoopOnEvent: true
    txtOwnerId: home-cluster
    txtPrefix: "k8s."

  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: *name
            patch: |
              - op: add
                path: /spec/template/spec/enableServiceLinks
                value: false
