---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-homeops
spec:
  provider:
    onepasswordSDK:
      vault: HomeOps
      auth:
        serviceAccountSecretRef:
          name: onepassword-kubernetes
          key: token
          namespace: external-secrets
